# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_2_graphic.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName(_fromUtf8("HomePage"))
        HomePage.setEnabled(True)
        HomePage.resize(1280, 700)
        HomePage.setMinimumSize(QtCore.QSize(1280, 700))
        HomePage.setMaximumSize(QtCore.QSize(1280, 700))
        HomePage.setStyleSheet(_fromUtf8("QMainWindow {\n"
"background-color: black;\n"
"}\n"
"\n"
""))
        self.centralwidget = QtGui.QWidget(HomePage)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.date = QtGui.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(40, 50, 271, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.date.setFont(font)
        self.date.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.date.setObjectName(_fromUtf8("date"))
        self.logo_ubc = QtGui.QLabel(self.centralwidget)
        self.logo_ubc.setGeometry(QtCore.QRect(40, 610, 423, 57))
        self.logo_ubc.setText(_fromUtf8(""))
        self.logo_ubc.setPixmap(QtGui.QPixmap(_fromUtf8("resources/1_2016_UBCStandard_Signature_ReverseRGB72.png")))
        self.logo_ubc.setScaledContents(True)
        self.logo_ubc.setObjectName(_fromUtf8("logo_ubc"))
        self.logo_ece = QtGui.QLabel(self.centralwidget)
        self.logo_ece.setGeometry(QtCore.QRect(1050, 550, 231, 151))
        self.logo_ece.setText(_fromUtf8(""))
        self.logo_ece.setPixmap(QtGui.QPixmap(_fromUtf8("resources/ot5du1.png")))
        self.logo_ece.setScaledContents(True)
        self.logo_ece.setObjectName(_fromUtf8("logo_ece"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(990, 40, 241, 56))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.demo_num = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.demo_num.setFont(font)
        self.demo_num.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.demo_num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.demo_num.setObjectName(_fromUtf8("demo_num"))
        self.verticalLayout.addWidget(self.demo_num)
        self.group_num = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.group_num.setFont(font)
        self.group_num.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.group_num.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.group_num.setObjectName(_fromUtf8("group_num"))
        self.verticalLayout.addWidget(self.group_num)
        self.layoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 530, 1211, 53))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.output_group_1 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.output_group_1.setObjectName(_fromUtf8("output_group_1"))
        self.output_4 = QtGui.QVBoxLayout()
        self.output_4.setObjectName(_fromUtf8("output_4"))
        self.name_4 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_4.setFont(font)
        self.name_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.name_4.setText(_fromUtf8(""))
        self.name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.name_4.setObjectName(_fromUtf8("name_4"))
        self.output_4.addWidget(self.name_4)
        self.data_4 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_4.setFont(font)
        self.data_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.data_4.setText(_fromUtf8(""))
        self.data_4.setAlignment(QtCore.Qt.AlignCenter)
        self.data_4.setObjectName(_fromUtf8("data_4"))
        self.output_4.addWidget(self.data_4)
        self.output_group_1.addLayout(self.output_4)
        self.output_5 = QtGui.QVBoxLayout()
        self.output_5.setObjectName(_fromUtf8("output_5"))
        self.name_5 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_5.setFont(font)
        self.name_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.name_5.setText(_fromUtf8(""))
        self.name_5.setAlignment(QtCore.Qt.AlignCenter)
        self.name_5.setObjectName(_fromUtf8("name_5"))
        self.output_5.addWidget(self.name_5)
        self.data_5 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_5.setFont(font)
        self.data_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.data_5.setText(_fromUtf8(""))
        self.data_5.setAlignment(QtCore.Qt.AlignCenter)
        self.data_5.setObjectName(_fromUtf8("data_5"))
        self.output_5.addWidget(self.data_5)
        self.output_group_1.addLayout(self.output_5)
        self.output_6 = QtGui.QVBoxLayout()
        self.output_6.setObjectName(_fromUtf8("output_6"))
        self.name_6 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_6.setFont(font)
        self.name_6.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.name_6.setText(_fromUtf8(""))
        self.name_6.setAlignment(QtCore.Qt.AlignCenter)
        self.name_6.setObjectName(_fromUtf8("name_6"))
        self.output_6.addWidget(self.name_6)
        self.data_6 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_6.setFont(font)
        self.data_6.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.data_6.setText(_fromUtf8(""))
        self.data_6.setAlignment(QtCore.Qt.AlignCenter)
        self.data_6.setObjectName(_fromUtf8("data_6"))
        self.output_6.addWidget(self.data_6)
        self.output_group_1.addLayout(self.output_6)
        self.output_7 = QtGui.QVBoxLayout()
        self.output_7.setObjectName(_fromUtf8("output_7"))
        self.name_7 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_7.setFont(font)
        self.name_7.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.name_7.setText(_fromUtf8(""))
        self.name_7.setAlignment(QtCore.Qt.AlignCenter)
        self.name_7.setObjectName(_fromUtf8("name_7"))
        self.output_7.addWidget(self.name_7)
        self.data_7 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_7.setFont(font)
        self.data_7.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.data_7.setText(_fromUtf8(""))
        self.data_7.setAlignment(QtCore.Qt.AlignCenter)
        self.data_7.setObjectName(_fromUtf8("data_7"))
        self.output_7.addWidget(self.data_7)
        self.output_group_1.addLayout(self.output_7)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 472, 1211, 53))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.output_group_0 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.output_group_0.setObjectName(_fromUtf8("output_group_0"))
        self.output_0 = QtGui.QVBoxLayout()
        self.output_0.setObjectName(_fromUtf8("output_0"))
        self.name_0 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_0.setFont(font)
        self.name_0.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.name_0.setText(_fromUtf8(""))
        self.name_0.setAlignment(QtCore.Qt.AlignCenter)
        self.name_0.setObjectName(_fromUtf8("name_0"))
        self.output_0.addWidget(self.name_0)
        self.data_0 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_0.setFont(font)
        self.data_0.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.data_0.setText(_fromUtf8(""))
        self.data_0.setAlignment(QtCore.Qt.AlignCenter)
        self.data_0.setObjectName(_fromUtf8("data_0"))
        self.output_0.addWidget(self.data_0)
        self.output_group_0.addLayout(self.output_0)
        self.output_1 = QtGui.QVBoxLayout()
        self.output_1.setObjectName(_fromUtf8("output_1"))
        self.name_1 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_1.setFont(font)
        self.name_1.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.name_1.setText(_fromUtf8(""))
        self.name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_1.setObjectName(_fromUtf8("name_1"))
        self.output_1.addWidget(self.name_1)
        self.data_1 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_1.setFont(font)
        self.data_1.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.data_1.setText(_fromUtf8(""))
        self.data_1.setAlignment(QtCore.Qt.AlignCenter)
        self.data_1.setObjectName(_fromUtf8("data_1"))
        self.output_1.addWidget(self.data_1)
        self.output_group_0.addLayout(self.output_1)
        self.output_2 = QtGui.QVBoxLayout()
        self.output_2.setObjectName(_fromUtf8("output_2"))
        self.name_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_2.setFont(font)
        self.name_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.name_2.setText(_fromUtf8(""))
        self.name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.name_2.setObjectName(_fromUtf8("name_2"))
        self.output_2.addWidget(self.name_2)
        self.data_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_2.setFont(font)
        self.data_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.data_2.setText(_fromUtf8(""))
        self.data_2.setAlignment(QtCore.Qt.AlignCenter)
        self.data_2.setObjectName(_fromUtf8("data_2"))
        self.output_2.addWidget(self.data_2)
        self.output_group_0.addLayout(self.output_2)
        self.output_3 = QtGui.QVBoxLayout()
        self.output_3.setObjectName(_fromUtf8("output_3"))
        self.name_3 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_3.setFont(font)
        self.name_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.name_3.setText(_fromUtf8(""))
        self.name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.name_3.setObjectName(_fromUtf8("name_3"))
        self.output_3.addWidget(self.name_3)
        self.data_3 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.data_3.setFont(font)
        self.data_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.data_3.setText(_fromUtf8(""))
        self.data_3.setAlignment(QtCore.Qt.AlignCenter)
        self.data_3.setObjectName(_fromUtf8("data_3"))
        self.output_3.addWidget(self.data_3)
        self.output_group_0.addLayout(self.output_3)
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 100, 691, 371))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.device_container = QtGui.QVBoxLayout(self.layoutWidget2)
        self.device_container.setObjectName(_fromUtf8("device_container"))
        self.layoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(720, 100, 361, 191))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.plot_container_0 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.plot_container_0.setObjectName(_fromUtf8("plot_container_0"))
        self.layoutWidget_4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(720, 290, 361, 181))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.plot_container_1 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.plot_container_1.setObjectName(_fromUtf8("plot_container_1"))
        self.mode_0 = QtGui.QLabel(self.centralwidget)
        self.mode_0.setGeometry(QtCore.QRect(1082, 132, 149, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.mode_0.setFont(font)
        self.mode_0.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,30);"))
        self.mode_0.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_0.setObjectName(_fromUtf8("mode_0"))
        self.mode_1 = QtGui.QLabel(self.centralwidget)
        self.mode_1.setGeometry(QtCore.QRect(1082, 189, 149, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.mode_1.setFont(font)
        self.mode_1.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,30);"))
        self.mode_1.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_1.setObjectName(_fromUtf8("mode_1"))
        self.mode_2 = QtGui.QLabel(self.centralwidget)
        self.mode_2.setGeometry(QtCore.QRect(1082, 246, 149, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.mode_2.setFont(font)
        self.mode_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,30);"))
        self.mode_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_2.setObjectName(_fromUtf8("mode_2"))
        self.mode_3 = QtGui.QLabel(self.centralwidget)
        self.mode_3.setGeometry(QtCore.QRect(1082, 303, 149, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        self.mode_3.setFont(font)
        self.mode_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,30);"))
        self.mode_3.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_3.setObjectName(_fromUtf8("mode_3"))
        self.mode_4 = QtGui.QLabel(self.centralwidget)
        self.mode_4.setGeometry(QtCore.QRect(1082, 360, 149, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.mode_4.setFont(font)
        self.mode_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,30);"))
        self.mode_4.setScaledContents(True)
        self.mode_4.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_4.setObjectName(_fromUtf8("mode_4"))
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.logo_ubc.raise_()
        self.logo_ece.raise_()
        self.date.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_2.raise_()
        self.layoutWidget_4.raise_()
        self.mode_4.raise_()
        HomePage.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        HomePage.setWindowTitle(_translate("HomePage", "ELEC 391 Demo 2", None))
        self.date.setText(_translate("HomePage", "February 20, 2017", None))
        self.demo_num.setText(_translate("HomePage", "ELEC 391 Demo II", None))
        self.group_num.setText(_translate("HomePage", "W2016 T2 Team C3", None))
        self.mode_0.setText(_translate("HomePage", "<html><head/><body><p><br/></p></body></html>", None))
        self.mode_1.setText(_translate("HomePage", "<html><head/><body><p><br/></p></body></html>", None))
        self.mode_2.setText(_translate("HomePage", "<html><head/><body><p><br/></p></body></html>", None))
        self.mode_3.setText(_translate("HomePage", "<html><head/><body><p><br/></p></body></html>", None))
        self.mode_4.setText(_translate("HomePage", "<html><head/><body><p/><p/><p/></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    HomePage = QtGui.QMainWindow()
    ui = Ui_HomePage()
    ui.setupUi(HomePage)
    HomePage.show()
    sys.exit(app.exec_())

